### ISSUE TITLE
README is lacking some information

### ISSUE THREAD

**Issue by vi** [shawnscode/crayon#58]
Is it about 2D or 3D games? What about sound support?

There should also be some screenshots.

**Comment by shawnscode** [comment]
Thanks!

The main crate is just some kind of coding framework, and the game specific features are built with sub-modules.

Anyway, audio supports should be parts of the core module. I'll trying to make it happens after finishing the first version of the [3d](https://github.com/shawnscode/crayon/modules/3d) sub-module.

**Comment by shawnscode** [comment]
Finally, the [audio](https://github.com/shawnscode/crayon/tree/master/modules/audio) module comes with version '0.6.0' (#64 ). And a little example could be found at [here](https://github.com/shawnscode/crayon/blob/master/examples/src/audio/audio.rs).
